### ISSUE TITLE
Make segment/subsegment closing thread-safe 

### ISSUE THREAD

**Issue by shengxil** [aws/aws-xray-sdk-java#108]
When closing a subsegment, we check if its parent segment is completed and has no other subsegment. If so we will emit the segment as well. This is because when we close a segment which parents live subsegments, we don't emit it but wait for all child subsegments complete. However, the current implementation is not thread-safe per below:

Customer ask:
"
Looking at the AWS X-Ray Java SDK code:

* https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/entities/EntityImpl.java#L496
* https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/entities/SegmentImpl.java#L53
The problems here are that (a) `LongAdder` is something of an "eventually consistent" counter and (b) checking `isInProgress` and `referenceCount` doesn't happen atomically. The end result is that both the segment and the subsegment itself may attempt to emit the subsegment.
To fix this, the following changes are needed:

* `referenceCount` must be turned into an `AtomicInteger` instead of `LongAdder`.
* The reference count must include the segment itself, i.e. it must start at 1 and reach zero when the segment has been closed. With this change, the separate `!isInProgress()` check can and must be removed.
* `Decrementing` and checking the value must be done atomically, i.e. `AtomicInteger#decrementAndGet()` instead of `LongAdder#decrement() followed by LongAdded#intValue()`.
"

**Comment by anoopgarlapati** [comment]
Hi @shengxil 
I'm facing a problem in my application for some of the traces for multi-threaded requests and I'm trying to understand if this is the same problem. Please excuse me if it is unrelated to this issue, I will raise it separately.

The problem is I'm receiving the following error log for some of the traces for multi-threaded requests.
```
2019-11-27 08:46:27.416 ERROR 3229 --- [ool-6-thread-24] c.a.x.e.EntityImpl                       : Exception while serializing entity.

com.fasterxml.jackson.databind.JsonMappingException: Index: 76, Size: 75 (through reference chain: com.amazonaws.xray.entities.SegmentImpl["subsegments"]->java.util.ArrayList[76])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:123) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3404) ~[jackson-databind-2.10.1.jar!/:2.10.1]
	at com.amazonaws.xray.entities.EntityImpl.serialize(EntityImpl.java:541) [aws-xray-recorder-sdk-core-2.3.0.jar!/:?]
	at com.amazonaws.xray.emitters.UDPEmitter.sendSegment(UDPEmitter.java:61) [aws-xray-recorder-sdk-core-2.3.0.jar!/:?]
	at com.amazonaws.xray.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:132) [aws-xray-recorder-sdk-core-2.3.0.jar!/:?]
	at com.amazonaws.xray.contexts.ThreadLocalSegmentContext.endSubsegment(ThreadLocalSegmentContext.java:46) [aws-xray-recorder-sdk-core-2.3.0.jar!/:?]
	at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:464) [aws-xray-recorder-sdk-core-2.3.0.jar!/:?]
	at com.amazonaws.xray.handlers.TracingHandler.finalizeSubsegment(TracingHandler.java:451) [aws-xray-recorder-sdk-aws-sdk-2.3.0.jar!/:?]
	at com.amazonaws.xray.handlers.TracingHandler.populateAndEndSubsegment(TracingHandler.java:427) [aws-xray-recorder-sdk-aws-sdk-2.3.0.jar!/:?]
	at com.amazonaws.xray.handlers.TracingHandler.populateAndEndSubsegment(TracingHandler.java:432) [aws-xray-recorder-sdk-aws-sdk-2.3.0.jar!/:?]
	at com.amazonaws.xray.handlers.TracingHandler.afterResponse(TracingHandler.java:347) [aws-xray-recorder-sdk-aws-sdk-2.3.0.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.afterResponse(AmazonHttpClient.java:1026) [aws-java-sdk-core-1.11.676.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:774) [aws-java-sdk-core-1.11.676.jar!/:?]
```
I am following the procedure in X-Ray documentation for passing segment context between threads as stated here - https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-multithreading.html and how its implemented in this example - https://docs.aws.amazon.com/xray/latest/devguide/scorekeep-workerthreads.html

This is leading to some of these X-Ray traces not showing up in X-Ray console even though they are sampled. I would like to know if this is caused by the problem mentioned here. If so, I would like to know the timeline for a fix to this issue.

Thanks
Anoop

**Comment by shengxil** [comment]
Hi Anoop,

Sorry for our late response. The error you pasted looks related to this concurrent issue. It is probably because when we serialize the segment, some other thread sent and removed a subsegment from it, which causes index out of bound. We are looking at some SynchronizedList replacement with lower performance impact. I will follow up on this thread.

Thanks,
Shengxin

**Comment by tofijak** [comment]
Any updates on this problem. I am getting the same exception when using multiple threads 

`
com.amazonaws.xray.entities.EntityImpl : Exception while serializing entity
com.fasterxml.jackson.databind.JsonMappingException: Index 1 out of bounds for length 1 (through reference chain: com.amazonaws.xray.entities.SegmentImpl["subsegments"]->java.util.ArrayList[1])`

**Comment by anuraaga** [comment]
@tofijak Sorry this slipped through the cracks, I'm going to take a look at this and get a fix in soon.

**Comment by tanmaymadaan** [comment]
Hi @anuraaga, does PR-250 resolve this? I'm using the latest release version 2.9.1, and getting the same error 

`com.amazonaws.xray.entities.EntityImpl : Exception while serializing entity`

Is there any workaround?

**Comment by anuraaga** [comment]
@tanmaymadaan 2.9.1 fixed some issues with deadlock, and we're hoping that serializing all accesses to a segment through a lock fixes the serialization error but it seems it may not have. Can you confirm the stack trace error message is also the same index out of bounds?

**Comment by anekar3416** [comment]
This issue is still appearing! Any update on this?
