### ISSUE TITLE
Spring library seems to depend on Spring Data

### ISSUE THREAD

**Issue by joodlehammond** [aws/aws-xray-sdk-java#140]
Hello!

Here are my dependencies: (library version 2.4.0)

```
    compile "com.amazonaws:aws-xray-recorder-sdk-core"
    compile "com.amazonaws:aws-xray-recorder-sdk-aws-sdk"
    compile "com.amazonaws:aws-xray-recorder-sdk-spring"
    compile "com.amazonaws:aws-xray-recorder-sdk-apache-http" 
    compile "com.amazonaws:aws-xray-recorder-sdk-slf4j"
```

Configuration is set up as per the AWS Documentation, **and works for all other services I have implemented so far**.
 
I am trying to implement X-Ray in a Spring application that doesn't connect to a database. This is the first service I've tried to add X-Ray to that has not worked.

I am getting the following error when I run my service:

```
Caused by: java.lang.IllegalArgumentException: warning no match for this type name: org.springframework.data.repository.Repository [Xlint:invalidAbsoluteTypeName]
	at org.aspectj.weaver.tools.PointcutParser.parsePointcutExpression(PointcutParser.java:319) ~[aspectjweaver-1.9.4.jar:na]
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.buildPointcutExpression(AspectJExpressionPointcut.java:227) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.obtainPointcutExpression(AspectJExpressionPointcut.java:198) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.aspectj.AspectJExpressionPointcut.getClassFilter(AspectJExpressionPointcut.java:177) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:225) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:288) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:320) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:126) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:95) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:76) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:347) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299) ~[spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:429) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	... 25 common frames omitted
```

After a bit of debugging, and making sure I didn't depend on any of the database related X-Ray libraries, I found that the library for Spring `aws-xray-recorder-sdk-spring:2.4.0` depends on spring data classes:

_Lines 69 to 71 of the `com.amazonaws.xray.spring.aop.AbstractXRayInterceptor.java`_
```
    @Pointcut("execution(public !void org.springframework.data.repository.Repository+.*(..))")
    protected void springRepositories() {
    }
```

I feel that this should only be a dependency when using the database related X-Ray libraries. Is there any way around this?

**Comment by joodlehammond** [comment]
Turns out there is an **undocumented** `BaseAbstractXRayInterceptor.java` class that is created for this exact purpose:

_From [com.amazonaws.xray.spring.aop.BaseAbstractXRayInterceptor](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-spring/src/main/java/com/amazonaws/xray/spring/aop/BaseAbstractXRayInterceptor.java)_

Why the normal `AbstractXRayInterceptor` is the default for the documentation confuses me. But either way, I hope this helps someone.

**Comment by joodlehammond** [comment]
It appears that this class is not available in the 2.4.0 artifact? This class was added in January, and the last X Ray release in Maven was in November. Do you have a time line for release?

**Comment by willarmiros** [comment]
Hi @joodlehammond, 
Unfortunately we cannot provide official timelines for our releases, but that change will be included in the next one! Feel free to "watch" this repo to get notified when we make it.

**Comment by bhautikpip** [comment]
We release v2.5.0 Java SDK yesterday. So resolving.

**Comment by joodlehammond** [comment]
Thanks guys, can't wait to try it out!
