### ISSUE TITLE
XrayClientException: Could not serialize and send request

### ISSUE THREAD

**Issue by RuslanKharevych** [aws/aws-xray-sdk-java#185]
Getting ```XrayClientException: Could not serialize and send request ``` periodically(every 5 minutes, 30-40 seconds between messages). For example:
First message - 2020-07-24 17:48:37.519;
Second message - 2020-07-24 17:49:16.174;
Third message - 2020-07-24 17:53:37.520;
Fourth message - 2020-07-24 17:54:17.174.

Stacktrace:
```2020-07-24 15:03:37,518 ERROR [pool-8-thread-1] [] [RulePoller.java:74] - Encountered error polling GetSamplingRules:  MEX com.amazonaws.xray.internal.XrayClientException: Could not serialize and send request. 	at com.amazonaws.xray.internal.UnsignedXrayClient.sendRequest(UnsignedXrayClient.java:118) ~[aws-xray-recorder-sdk-core-2.6.0.jar:na] 	at com.amazonaws.xray.internal.UnsignedXrayClient.getSamplingRules(UnsignedXrayClient.java:88) ~[aws-xray-recorder-sdk-core-2.6.0.jar:na] 	at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.pollRule(RulePoller.java:100) ~[aws-xray-recorder-sdk-core-2.6.0.jar:na] 	at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.lambda$start$0(RulePoller.java:72) ~[aws-xray-recorder-sdk-core-2.6.0.jar:na] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na] 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na] 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na] Caused by: java.net.ConnectException: Connection refused 	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na] 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source) ~[na:na] 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source) ~[na:na] 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[na:na] 	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na] 	at java.base/sun.net.NetworkClient.doConnect(Unknown Source) ~[na:na] 	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na] 	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:na] 	at java.base/sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:na] 	at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na] 	at java.base/sun.net.www.http.HttpClient.New(Unknown Source) ~[na:na] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:na] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:na] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:na] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:na] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[na:na] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[na:na] 	at com.amazonaws.xray.internal.UnsignedXrayClient.sendRequest(UnsignedXrayClient.java:115) ~[aws-xray-recorder-sdk-core-2.6.0.jar:na] 	... 9 common frames omitted ```

**Comment by shengxil** [comment]
Hello RuslanKharevych,

From the error log it seems like your application was not able to retrieve X-Ray sampling rule from X-Ray daemon. See https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html#xray-console-sampling-nextsteps

> When the X-Ray SDK calls sampling APIs, it uses the X-Ray daemon as a proxy.

Please make sure the X-Ray daemon is up running and feel free to send us the [daemon log](https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-configuration.html) to diagnose.

Thanks,
Shengxin

**Comment by zaf187** [comment]
@shengxil Hi,

I am having the same issue with my client, i am using the following client version;
```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-xray-recorder-sdk-spring</artifactId>
    <version>2.8.0</version>
</dependency>
```
My x-ray daemon is running in Docker using the latest image;
amazon/aws-xray-daemon
https://hub.docker.com/r/amazon/aws-xray-daemon
looks like the latest was updated 7 days ago from the time of this post.

I am getting the same stack trace in my code, periodically;
```
2021-03-04 22:19:30.227  ERROR 14744 --- [pool-9-thread-1] c.a.x.s.sampling.pollers.RulePoller      : Encountered error polling GetSamplingRules: 

com.amazonaws.xray.internal.XrayClientException: Could not serialize and send request.
	at com.amazonaws.xray.internal.UnsignedXrayClient.sendRequest(UnsignedXrayClient.java:142) ~[aws-xray-recorder-sdk-core-2.8.0.jar:na]
	at com.amazonaws.xray.internal.UnsignedXrayClient.getSamplingRules(UnsignedXrayClient.java:112) ~[aws-xray-recorder-sdk-core-2.8.0.jar:na]
	at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.pollRule(RulePoller.java:100) ~[aws-xray-recorder-sdk-core-2.8.0.jar:na]
	at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.lambda$start$0(RulePoller.java:72) ~[aws-xray-recorder-sdk-core-2.8.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_221]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) ~[na:1.8.0_221]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_221]
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_221]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_221]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_221]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_221]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_221]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_221]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_221]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_221]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_221]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_221]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_221]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_221]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_221]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[na:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[na:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[na:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[na:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340) ~[na:1.8.0_221]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315) ~[na:1.8.0_221]
	at com.amazonaws.xray.internal.UnsignedXrayClient.sendRequest(UnsignedXrayClient.java:139) ~[aws-xray-recorder-sdk-core-2.8.0.jar:na]
	... 11 common frames omitted
```
and my Daemon logs;
```
2021-03-04T22:07:41Z [Info] Initializing AWS X-Ray daemon 3.2.0
2021-03-04T22:07:41Z [Debug] Listening on UDP 0.0.0.0:2000
2021-03-04T22:07:41Z [Info] Using buffer memory limit of 64 MB
2021-03-04T22:07:41Z [Info] 1024 segment buffers allocated
2021-03-04T22:07:41Z [Debug] Using proxy address:
2021-03-04T22:07:41Z [Debug] Fetch region us-east-2 from commandline/config file
2021-03-04T22:07:41Z [Info] Using region: us-east-2
2021-03-04T22:07:41Z [Debug] ARN of the AWS resource running the daemon:
2021-03-04T22:07:41Z [Debug] No Metadata set for telemetry records
2021-03-04T22:07:41Z [Debug] Using Endpoint: https://xray.us-east-2.amazonaws.com
2021-03-04T22:07:41Z [Debug] Telemetry initiated
2021-03-04T22:07:41Z [Info] HTTP Proxy server using X-Ray Endpoint : https://xray.us-east-2.amazonaws.com
2021-03-04T22:07:41Z [Debug] Using Endpoint: https://xray.us-east-2.amazonaws.com
2021-03-04T22:07:41Z [Debug] Batch size: 50
2021-03-04T22:07:41Z [Info] Starting proxy http server on 0.0.0.0:2000
2021-03-04T22:08:41Z [Debug] Skipped telemetry data as no segments found
2021-03-04T22:09:41Z [Debug] Skipped telemetry data as no segments found
2021-03-04T22:10:41Z [Debug] Skipped telemetry data as no segments found
2021-03-04T22:11:41Z [Debug] Skipped telemetry data as no segments found
2021-03-04T22:12:41Z [Debug] Skipped telemetry data as no segments found
2021-03-04T22:13:41Z [Debug] Skipped telemetry data as no segments found
2021-03-04T22:14:28Z [Debug] processor: sending partial batch
2021-03-04T22:14:28Z [Debug] processor: segment batch size: 1. capacity: 50
2021-03-04T22:14:29Z [Info] Successfully sent batch of 1 segments (0.656 seconds)
2021-03-04T22:14:41Z [Debug] Send 1 telemetry record(s)
2021-03-04T22:15:24Z [Debug] processor: sending partial batch
2021-03-04T22:15:24Z [Debug] processor: segment batch size: 1. capacity: 50
2021-03-04T22:15:24Z [Info] Successfully sent batch of 1 segments (0.158 seconds)
2021-03-04T22:15:41Z [Debug] Send 1 telemetry record(s)
2021-03-04T22:15:47Z [Debug] processor: sending partial batch
2021-03-04T22:15:47Z [Debug] processor: segment batch size: 1. capacity: 50
2021-03-04T22:15:47Z [Info] Successfully sent batch of 1 segments (0.122 seconds)
2021-03-04T22:16:42Z [Debug] Send 1 telemetry record(s)
2021-03-04T22:17:42Z [Debug] Send 1 telemetry record(s)
2021-03-04T22:18:43Z [Debug] Send 1 telemetry record(s)
2021-03-04T22:19:43Z [Debug] Send 1 telemetry record(s)
2021-03-04T22:20:44Z [Debug] Failed to send telemetry 1 record(s). Re-queue records. SerializationError: failed to unmarshal response error
        status code: 400, request id:
caused by: UnmarshalError: failed decoding error message
        00000000  3c 68 74 6d 6c 3e 0d 0a  3c 68 65 61 64 3e 3c 74  |<html>..<head><t|
00000010  69 74 6c 65 3e 34 30 30  20 42 61 64 20 52 65 71  |itle>400 Bad Req|
00000020  75 65 73 74 3c 2f 74 69  74 6c 65 3e 3c 2f 68 65  |uest</title></he|
00000030  61 64 3e 0d 0a 3c 62 6f  64 79 3e 0d 0a 3c 63 65  |ad>..<body>..<ce|
00000040  6e 74 65 72 3e 3c 68 31  3e 34 30 30 20 42 61 64  |nter><h1>400 Bad|
00000050  20 52 65 71 75 65 73 74  3c 2f 68 31 3e 3c 2f 63  | Request</h1></c|
00000060  65 6e 74 65 72 3e 0d 0a  3c 2f 62 6f 64 79 3e 0d  |enter>..</body>.|
00000070  0a 3c 2f 68 74 6d 6c 3e  0d 0a                    |.</html>..|

caused by: invalid character '<' looking for beginning of value
2021-03-04T22:21:45Z [Debug] Send 2 telemetry record(s)
2021-03-04T22:22:45Z [Debug] Send 1 telemetry record(s)
```

**Comment by bhautikpip** [comment]
Hi @zaf187 ,

Would you mind opening an issue on [X-Ray daemon](https://github.com/aws/aws-xray-daemon) repository? I think this issue is more related to daemon than X-Ray Java SDK. I think we probably have to investigate why we are receiving such response from back end and maybe if these errors are frequent then we also might think of adding a handling case in the case of such errors.
