### ISSUE TITLE
UnsupportedOperationException - FacadeSegments cannot be mutated

### ISSUE THREAD

**Issue by ambethell** [aws/aws-xray-sdk-java#19]
Occasionally the following exception thrown from a Lambda:

`java.lang.UnsupportedOperationException: FacadeSegments cannot be mutated.
    at com.amazonaws.xray.entities.FacadeSegment.addException(FacadeSegment.java:341)
    at com.amazonaws.xray.spring.aop.AbstractXRayInterceptor.processXRayTrace(AbstractXRayInterceptor.java:53)
    at com.amazonaws.xray.spring.aop.AbstractXRayInterceptor.traceAroundMethods(AbstractXRayInterceptor.java:44)
    at sun.reflect.GeneratedMethodAccessor58.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:643)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:632)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
    at com.umusic.work.generator.WorkRecordGeneratorImpl$$EnhancerBySpringCGLIB$$cc14bb97.processWork(<generated>)
    at com.umusic.work.generator.WorkRecordGeneratorHandler.handleRequest(WorkRecordGeneratorHandler.java:51)
    at com.umusic.work.generator.WorkRecordGeneratorHandler.handleRequest(WorkRecordGeneratorHandler.java:21)
    at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:178)
    at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
    at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:283)
    at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
    at java.lang.Class.forName0(Class.java)
    at java.lang.Class.forName(Class.java:348)
    at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)`

Apart from that the instrumentation appears to be working fine - I'm using the latest version 1.3.1 - of aws-xray-record-sdk-spring, and have tried 1.1.0 and 1.2.0 of aws-lambda-java-core

What does this exception mean?

**Comment by awssandra** [comment]
Hi ambethell,

The way that AWS Lambda works with X-Ray is slightly different than the non-Lambda experience.

When a Lambda function starts, Lambda creates a root segment as a part of their own start-up code, before even touching the customer code at all. This is to capture the Lambda overall cold start time, and any data they add from their service point-of-view.

The idea was to create a "seamless" trace between service code and customer code for the Lambda experience. However, due to the strict policies of Lambda to not touch customer code (and their service built safeties around this concept), this was not possible for our v1 integration.

As a work around, we split it into 2 parts - the Lambda-generated segment and the additional SDK subsegments. Lambda sends it's segment when it reaches the point where it runs customer code, and it propagates the ID, parent ID and sampling decision (of the original segment) via environment variables which is picked up by the X-Ray SDK. The X-Ray SDK in turn detects it's running in Lambda and, under the hood, the SDK constructs a "facade" segment using this data. It's a fake segment, which looks and acts like a real segment for all intents and purposes, but it merely acts as a placeholder, and sends the subsegments attached to the X-Ray service on close. The facade segment cannot hold any additional data or be modified because the segment with it's unique ID has already been received by the X-Ray service.

So, to notify the user when the facade segment is attempting to be modified, we throw the exception "FacadeSegments cannot be mutated." We do intend to fix this behavior with Lambda in the near future, as it is not ideal.

To continue, the issue here is that there is an exception that's attempting to be added to the facade segment, which shouldn't happen. It seems there's an exception from the processXRayTrace method.

https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-spring/src/main/java/com/amazonaws/xray/spring/aop/AbstractXRayInterceptor.java#L53

Could you override the method and log the originating error?

Thanks,
Sandta

**Comment by ambethell** [comment]
Thanks for clearing things up - there was an exception being thrown from our code.

**Comment by girotomas** [comment]
If the user creates a segment then we don't get any lambda coldstart time info. Only if the user creates subsegments, it works.

**Comment by girotomas** [comment]
Additionally sometimes we want to modify the parent segment to add annotations but this is failing with UnsupportedOperationException for me as in the original post.
