### ISSUE TITLE
Not subsegment found exception inside AOP Interceptor

### ISSUE THREAD

**Issue by friscoMad** [aws/aws-xray-sdk-java#231]
I am getting random errors with the AOP Interceptor it may be related to sampling but I am not totally sure.

Full stack trace:
```
[UncaughtExceptions] com.amazonaws.xray.exceptions.SubsegmentNotFoundException: Failed to end subsegment: subsegment cannot be found.
com.amazonaws.xray.exceptions.SubsegmentNotFoundException: Failed to end subsegment: subsegment cannot be found.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.amazonaws.xray.strategy.RuntimeErrorContextMissingStrategy.contextMissing(RuntimeErrorContextMissingStrategy.java:32)
	at com.amazonaws.xray.contexts.ThreadLocalSegmentContext.endSubsegment(ThreadLocalSegmentContext.java:93)
	at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:612)
	at com.amazonaws.xray.AWSXRay.endSubsegment(AWSXRay.java:124)
	at com.amazonaws.xray.spring.aop.BaseAbstractXRayInterceptor.processXRayTrace(BaseAbstractXRayInterceptor.java:58)
	at com.amazonaws.xray.spring.aop.BaseAbstractXRayInterceptor.traceAroundMethods(BaseAbstractXRayInterceptor.java:43)
	at jdk.internal.reflect.GeneratedMethodAccessor335.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.returnly.services.product.provider.ShopifyProductProvider$$EnhancerBySpringCGLIB$$5244eb34.getProducts(<generated>) [10 skipped]
	at com.returnly.services.product.ProductService.getCollectionProducts(ProductService.kt:68)
	at com.returnly.services.product.ProductService$$FastClassBySpringCGLIB$$df39c3f1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) [3 skipped]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at com.returnly.services.product.ProductService$$EnhancerBySpringCGLIB$$3023bde0.getCollectionProducts(<generated>) [3 skipped]
	at com.returnly.services.product.ProductController.getCollectionProducts(ProductController.kt:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503) [11 skipped]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) [1 skipped]
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:65) [4 skipped]
	at com.returnly.core.spring.WebAppConfiguration$responseInjectingTraceFilter$1.doFilterInternal(WebAppConfiguration.kt:212) [1 skipped]
	at org.zalando.logbook.servlet.NormalStrategy.doFilter(NormalStrategy.java:38) [2 skipped]
	at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:39)
	at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:31)
	at com.returnly.core.spring.web.RequestMetadata.doFilterInternal(RequestMetadata.kt:77) [1 skipped]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) [2 skipped]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [1 skipped]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [1 skipped]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:50) [9 skipped]
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:82) [1 skipped]
	at org.springframework.cloud.sleuth.instrument.web.LazyTracingFilter.doFilter(TraceWebServletAutoConfiguration.java:138)
	at org.zalando.logbook.servlet.SecurityStrategy.doFilter(SecurityStrategy.java:33) [1 skipped]
	at org.zalando.logbook.servlet.LogbookFilter.doFilter(LogbookFilter.java:39)
	at org.zalando.logbook.servlet.HttpFilter.doFilter(HttpFilter.java:31)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108) [1 skipped]
	at com.returnly.core.spring.web.StartTimeTrackingFilter.doFilterInternal(StartTimeTrackingFilter.kt:17) [5 skipped]
	at com.amazonaws.xray.javax.servlet.AWSXRayServletFilter.doFilter(AWSXRayServletFilter.java:188) [2 skipped]
	at java.base/java.lang.Thread.run(Thread.java:834) [32 skipped]
```

Here you can see the full debug traces of the request process, they are in reverse (most recent at the top).
I don't see that "prepareHandle" subsegment being closed but still this fails.
```
[UncaughtExceptions] com.amazonaws.xray.exceptions.SubsegmentNotFoundException: Failed to end subsegment: subsegment cannot be found. com.amazonaws.xray.exceptions.SubsegmentNotFoundException: Failed to end subsegment: subsegment cannot be found. at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) at com.amazonaws.xray.strategy.RuntimeErrorContextMissingStrategy.contextMissing(RuntimeErrorContextMissingStrategy.java:32) at com.amazonaws.xray.contexts.ThreadLocalSegmentContext.endSubsegment(ThreadLocalSegmentContext.java:93) at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:612) at com.amazonaws.xray.AWSXRay
[LoggingConnection] ROLLBACK in HikariPool-2 (HikariProxyConnection@1738357704 wrapping org.postgresql.jdbc.PgConnection@472eda9f)
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[ThreadLocalSegmentContext] Ending subsegment named:
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: true
[ThreadLocalSegmentContext] Beginning subsegment named: product_svc@services-db-ro
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[ThreadLocalSegmentContext] Ending subsegment named:
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: true
[ThreadLocalSegmentContext] Beginning subsegment named: product_svc@services-db-ro
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[ThreadLocalSegmentContext] Ending subsegment named:
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: true
[ThreadLocalSegmentContext] Beginning subsegment named: product_svc@services-db-ro
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[ThreadLocalSegmentContext] Ending subsegment named:
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: true
[ThreadLocalSegmentContext] Beginning subsegment named: product_svc@services-db-ro
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[ShopifyClient] Fetched 6 Product records
[ThreadLocalSegmentContext] Ending subsegment named:
[Logbook] Incoming Response: Duration: 182 ms HTTP/1.1 200 OK Server: cloudflare X-Request-Id: 000 cf-request-id: 0000 X-Shopify-Shop-Api-Call-Limit: 1/40 {XXXX}
[Logbook] Outgoing Request: GET https://EXTERNAL_API/XXXX HTTP/1.1
[ThreadLocalSegmentContext] Beginning subsegment named: EXTERNAL_API
[ThreadLocalSegmentContext] Beginning subsegment named: getProducts
[ThreadLocalSegmentContext] Ending subsegment named:
[ThreadLocalSegmentContext] Beginning subsegment named: prepareHandle
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[ThreadLocalSegmentContext] Ending subsegment named:
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: true
[ThreadLocalSegmentContext] Beginning subsegment named: product_svc@services-db-ro
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[TracingStatement] Invoking statement execution with X-Ray tracing. Tracing active: false
[Logbook] Incoming Request: GET http://XXXXX/CCCCC HTTP/1.1 x-request-id: b531854e-e9f5-4589-b328-fd0f2e9cf9bc User-Agent: returns-center Content-Length: 0
[AWSXRayServletFilter] Creating Dummy Segment
[AWSXRayServletFilter] Sampling strategy decided NOT_SAMPLED.
```

**Comment by friscoMad** [comment]
Closing as this seems to be fixed by #215
2.7.1 fails to close subsegments that have a nested subsegment.
