### ISSUE TITLE
Lambda context cannot create an initial subsegment and causes a ClassCastException

### ISSUE THREAD

**Issue by bvingerh** [aws/aws-xray-sdk-java#245]
I'm using aws-xray-recorder-sdk-core version 2.8.0

Exception message and partial trace:
```
class com.amazonaws.xray.entities.SegmentImpl cannot be cast to class com.amazonaws.xray.entities.Subsegment (com.amazonaws.xray.entities.SegmentImpl and com.amazonaws.xray.entities.Subsegment are in unnamed module of loader lambdainternal.CustomerClassLoader @5f184fc6): java.lang.ClassCastException
java.lang.ClassCastException: class com.amazonaws.xray.entities.SegmentImpl cannot be cast to class com.amazonaws.xray.entities.Subsegment (com.amazonaws.xray.entities.SegmentImpl and com.amazonaws.xray.entities.Subsegment are in unnamed module of loader lambdainternal.CustomerClassLoader @5f184fc6)
	at com.amazonaws.xray.contexts.LambdaSegmentContext.beginSubsegment(LambdaSegmentContext.java:74)
	at com.amazonaws.xray.AWSXRayRecorder.beginSubsegment(AWSXRayRecorder.java:613)
	at com.id.cloud.runtime.compose.helpers.TraceHelper.lambda$beginSubsegment$7(TraceHelper.java:168)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at com.id.cloud.runtime.compose.helpers.TraceHelper.beginSubsegment(TraceHelper.java:165)
```
Invocation that led to the exception:
```java
AWSXRay.beginSegment("my segment", getRootTraceID(), getParentID());
//...
AWSXRay.getCurrentSegmentOptional().ifPresent(segment -> AWSXRay.beginSubsegment("my new subsegment"));
```
The code works correctly when running local JUnit tests, because then `com.amazonaws.xray.contexts.ThreadLocalSegmentContext` is used as context. However, when deploying the code in an AWS Lambda, `com.amazonaws.xray.contexts.LambdaSegmentContext` is used, which has a rather different implementation for `beginSubsegment`: both the ThreadLocal and the Lambda implementation obtain the current trace entity via a call to `getTraceEntity()` and both perform a nullcheck on the result. However, the ThreadLocal implementation then creates a new subsegment using the current entity as parent, while the Lambda implementation blandly assumes that the current entity must already be a Subsegment and downcasts it immediately, leading to a CCE when no subsegment was previously started (which, given the code, seems to be impossible from within the deployed lambda).

**Comment by bvingerh** [comment]
I suppose the 'else' branch in `com.amazonaws.xray.contexts.LambdaSegmentContext#beginSubsegment` at line 73 could be replaced by
```java
} else { // Continuation of a subsegment branch.
    Segment parentSegment = entity.getParentSegment();
    // Ensure customers have not leaked subsegments across invocations
    TraceID environmentRootTraceId = LambdaSegmentContext.getTraceHeaderFromEnvironment().getRootTraceId();
    if (environmentRootTraceId != null &&
        !environmentRootTraceId.equals(entity.getParentSegment().getTraceId())) {
        clearTraceEntity();
        return beginSubsegment(recorder, name);
    }
    Subsegment subsegment = parentSegment.isRecording()
                            ? new SubsegmentImpl(recorder, name, parentSegment)
                            : Subsegment.noOp(parentSegment, recorder);
    subsegment.setParent(entity);
    entity.addSubsegment(subsegment);
    setTraceEntity(subsegment);

    List<SegmentListener> segmentListeners = recorder.getSegmentListeners();
    segmentListeners.stream()
            .filter(Objects::nonNull)
            .forEach(listener -> listener.onBeginSubsegment(subsegment));

    return subsegment;
}
```

**Comment by willarmiros** [comment]
Hi @bvingerh,

As I mentioned in my response in #246, we currently do not support custom segments created in Lambda function code, we only allow creating subsegments attached to the Lambda-provided segment. Hence the assumption made in the else branch that the parent entity will always be either `null` (in which case it's attached directly to the Lambda-provided segment in the backend) or the parent is another custom subsegment. 

That being said, throwing a `ClassCastException` is not a correct failure mode either. We should either:

1. Allow for a workaround of creating custom segments in Lambda, if you're open to making such a PR, as I proposed in #246, or
2. Change the beginSegment to a no-op in Lambda contexts so this bug can't happen, e.g. as we do in [Python](https://github.com/aws/aws-xray-sdk-python/blob/0081cdf4d8dc9c2976aee1204b718f9e809e3193/aws_xray_sdk/core/lambda_launcher.py#L54-L58)

Let me know what you think.

**Comment by rockey5520** [comment]
Hello @willarmiros 

Would you be able to give me a small example of how to create a subsegment attaching to the lambda provided segment, please? I am slightly struggling to achieve this workaround

Regards
Rakesh

**Comment by willarmiros** [comment]
@rockey5520 

```java

public class MyHandler implements RequestHandler {

  static {
    // Throws an exception, don't start a subsegment here
    // AWSXRay.beginSubsegment("bad subsegment");
  }

  // I don't remember the Lambda handler signature off top of my head
  public LambdaResponse myHandlerMethod() {
    Subsegment sub = AWSXRay.beginSubsegment("my subsegment");
    sub.addAnnotation("You can", "mutate me");

    // your code you'd like to wrap....

    AWSXRay.endSubsegment();
  }
}

```

**Comment by rockey5520** [comment]
@willarmiros Thanks this is helpful and it worked. 

I was wondering can I get all traces sent to X-ray using annotating all my classes(controllers, services, repositories) @XRayEnabled? Currently i am only can get traces upto one level(controller) but none of traces coming from other classes though such as service classes

my pointcut is `  @Pointcut("@within(com.amazonaws.xray.spring.aop.XRayEnabled) && bean(*)")`

 I am trying with REST api configured following example given in [https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-aop-spring.html](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-aop-spring.html)

**Comment by willarmiros** [comment]
Marking as bug since we shouldn't be throwing a ClassCastException no matter what

**Comment by otj202** [comment]
I got this error without ever calling beginSegment or beginSubSegment in my code. I added a AWSXRayServletFilter to my WebConfig, since otherwise the instrumentor doesn't add to the existing trace if some other X-ray tracked service calls this one, it just starts a new trace. The servletfilter seems to solve this problem, except when you call the endpoint that reads to dynamo, in which case i get the classCast issue described above

**Comment by astsiatsko** [comment]
Hey guys, is still creation of segment  does not work in the latest version of xray libs? I tried to do my lambda project, but neither 
AWSXRayServletFilter nor AWSXRay.beginSegment works at all. How should I use it?
