### ISSUE TITLE
Workarounds and visibility on IOException: Message too long

### ISSUE THREAD

**Issue by steven-aerts** [aws/aws-xray-sdk-java#26]
We are running into the well known (#4) problem that sometimes a segment is too big to fit in a UDP message (65,507 bytes).  For example because it contains a big sql statement or an exception.

The problem is however that if these issues happen sporadically they are very difficult to debug as there is almost no visibility.

We see a few possible improvements which can be made easily:

* _Enhance visibility_: For example by logging the segment when it is too big.
It could be as easy as doing something like this:
```diff
     }
 
-    private boolean sendData(byte[] data) {
+    private boolean sendData(byte[] data, Entity entity) {
+        if (data.length > 65_527) {
+            logger.warn("(sub)segment is too big to send: " + entity.prettySerialize());
+            return false;
+        }
         DatagramPacket packet = new DatagramPacket(sendBuffer, DAEMON_BUF_RECEIVE_SIZE, config.address);
```
(Btw: it also puzzles us why `DAEMON_BUF_RECEIVE_SIZE` is a lot bigger then 65_527)

* _Add retry behavior_ which tries to send the completed subsegments (so if one is too big, it does not break the others).  We for example currently quickly implemented a `RetryingEmitter` which works like this:

```java
public class RetryingEmitter extends UDPEmitter {
    private static final Log logger = LogFactory.getLog(MethodHandles.lookup().lookupClass());
    private final StreamingStrategy streamingStrategy;
    public RetryingEmitter(StreamingStrategy streamingStrategy) throws SocketException {
        super();
        this.streamingStrategy = streamingStrategy;
    }
    public boolean sendSegment(Segment segment) {return trySplitOnFailure(segment, super::sendSegment);}
    public boolean sendSubsegment(Subsegment subsegment) {return trySplitOnFailure(subsegment, super::sendSubsegment);}
    <T extends Entity> boolean trySplitOnFailure(T entity, Predicate<T> send) {
        boolean ok = send.test(entity);
        if (!ok) {
            logger.info("send of entity " + entity.getId() + " failed, retrying.");
            streamingStrategy.streamSome(entity, this);
            ok = send.test(entity);
            if (!ok) {
                logger.warn("Unable to send entity " +  entity.getId() + " after split. size: " +
                        entity.serialize().length() + ", content: " + entity.prettySerialize());
            }
        }
        return ok;
    }
}
```
This is of course rather naive, as a lot of errors are still send.  But it helps us to debug these kinds of issues.

What do you think about these proposals?

Thanks,

    Steven

**Comment by haotianw465** [comment]
For 1, there is a try-catch block on UDP transmission so if the document is too large I think it will be logged. Also everyone has a different OS configuration on packet size so the hardcoded threshold for logging might not apply to everyone. You can still customize by extending the default emitter class to best suite you on threshold and log level etc. Thoughts?

For 2 it is a valid request. The SDK can provide a built-in emitter that streams subsegments when the whole documentation is too large. We can put this as an action item. A PR is also very welcome.

**Comment by steven-aerts** [comment]
For 1, 65 kilobyte is the maximum size of a UDP packet as it has [only 16-bits](https://en.wikipedia.org/wiki/User_Datagram_Protocol) to represent its length.
I agree with you it can be lower according to the os setting.
Our main problem is however that if it fails sporadically in a big codebase you have no clue which subsegment was the big guy causing the problem.  What about moving the log trace I propose to the catch block which throws the exception?

For 2: what do you think about the proposed class?  Especially on the strategy we have to pass to the emitter, is this something you are willing to accept.  Or maybe even better, can the PR add an extra method to the interface where the emitter can receive the strategy (and make it backwards compatible with a default method?
Or do you think this kind of code belongs more in the strategy class, as suggested [here](https://github.com/aws/aws-xray-sdk-java/issues/4#issuecomment-360367527).

**Comment by haotianw465** [comment]
Item 1 looks good to me. As for second item I would prefer subclassing emitter and have the retry-emitter as an opt-in. 

There is a lot of room for improvement including smarter streaming strategy and worker thread for serialization and UDP retry etc. But force streaming on UDP rejection is an easy change that provides immediate value.

**Comment by zxkane** [comment]
> With the introduction of PR #91, I think step 2 has been mitigated. Let us know if you guys notice less "Message too long" errors as a result of it.
> 
> Thanks!

Still meet this exception when the `@XRayTraced` method throws an exception.

> @message
> 2019-11-22 15:04:35.164 ERROR 1 --- [nio-8080-exec-9] com.amazonaws.xray.emitters.UDPEmitter : Exception while sending segment over UDP for entity eCommence [6673a73e41512ac8] on segment [no parent segment]
> java.io.IOException: Message too large (sendto failed)
> at java.net.PlainDatagramSocketImpl.send(Native Method) ~[na:1.8.0_212]
> at java.net.DatagramSocket.send(DatagramSocket.java:693) ~[na:1.8.0_212]
> at com.amazonaws.xray.emitters.UDPEmitter.sendData(UDPEmitter.java:81) [aws-xray-recorder-sdk-core-2.3.0.jar!/:na]
> at com.amazonaws.xray.emitters.UDPEmitter.sendSegment(UDPEmitter.java:61) [aws-xray-recorder-sdk-core-2.3.0.jar!/:na]
> at com.amazonaws.xray.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:132) [aws-xray-recorder-sdk-core-2.3.0.jar!/:na]
> at com.amazonaws.xray.AWSXRayRecorder.endSegment(AWSXRayRecorder.java:394) [aws-xray-recorder-sdk-core-2.3.0.jar!/:na]
> at com.amazonaws.xray.javax.servlet.AWSXRayServletFilter.postFilter(AWSXRayServletFilter.java:394) [aws-xray-recorder-sdk-core-2.3.0.jar!/:na]
> at com.amazonaws.xray.javax.servlet.AWSXRayServletFilter.doFilter(AWSXRayServletFilter.java:169) [aws-xray-recorder-sdk-core-2.3.0.jar!/:na]
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
> at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
> at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.19.jar!/:9.0.19]
> at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) [spring-web-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]

**Comment by steven-aerts** [comment]
We are also still seeing the `message too long` error in 2.4.0.
We have the feeling it appear less, but it still appears.

We still have the feeling that a RetryingEmitter #58  which tries to stream Some of the segments when this situation is detected can help in this case.

@chanchiem what do you think?

**Comment by chanchiem** [comment]
Hmmm have you tried adjusting the maxSegmentSize for your streaming strategy? This is a threshold that must be met before subtree streaming even occurs. The tradeoff here is performance vs the probability of segments being too large to stream.

I.e, the smaller the number, the more subsegments will be streamed out and therefore a higher performance hit as it needs to serialize the subtree and stream it out.

Please take a look at the constructor [here](https://github.com/aws/aws-xray-sdk-java/blob/223863699c8405f9ebb33ca305f0fe4a18f81f87/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/DefaultStreamingStrategy.java#L40)

Please let us know if this reduces/completely removes the message too long errors.

**Comment by lucious7** [comment]
I'm facing the same problem even with a tiny `maxSegmentSize` (as low as 5 right now) when an exception is thrown or the SQL is big.

**Comment by willarmiros** [comment]
Hi @lucious7,

> when an exception is thrown or the SQL is big

When you say the "SQL is big" do you mean you're recording the results of your SQL queries in your subsegments? That can certainly cause your subsegment size to increase dramatically. I'd recommend only recording relevant pieces of your `ResultSet` in your subsegments if you're seeing the Message too long error. If your exception stack traces are very long and potentially also causing this error, consider constructing your `AWSXRayRecorder` with a `DefaultThrowableSerializationStrategy` that sets a lower stack trace length ([constructor](https://github.com/aws/aws-xray-sdk-java/blob/ce4cb04127b9a983e276fab1a53645983d958500/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/DefaultThrowableSerializationStrategy.java#L54)). The default is 50, but you could try something like 15-20.

> as low as 5 right now

You could reduce `maxSegmentSize` to as low as 0 for immediate streaming of subsegments. There is a slight performance impact for streaming more frequently, but depending on your use case it's typically not that bad considering you're able to see all subsegments successfully with it.

**Comment by lucious7** [comment]
Thanks for the response @willarmiros. What I meant is when the query itself is big, with lengthy table and field names, lots of joins, etc.

I'll take a look at the recorder as you mentioned, thanks. I'm also still investigating the problem on my side. I'll check how it behaves with maxSegmentSize set to 0.
