### ISSUE TITLE
Deadlock when streaming some subsegments when parent is still open

### ISSUE THREAD

**Issue by steven-aerts** [aws/aws-xray-sdk-java#276]
Hi,

after an upstep to 2.9.0 we are seeing a deadlock in lock ordering, when multiple threads are adding segments to the same parent segment.

If you look at the stack traces you see the following behavior.

One thread is ending a subsegment and deciding to call `DefaultStreamingStrategy.streamSome` which takes the subsegmentsLock() to decide which it can stream.  When it finds a segment which is finished, it will try to get get lock on the parent segment to get its id[1].

But this lock is held by another thread, which tries to add a subsegment to the same parent, for that if first takes a lock on the parent segment and then it request the subsegmentLock() which is held by the first thread. [2]

We think this is a case of deadlock by lock ordering.

A possible solution might be to never take the subsegmentslock when the parent lock is not taken.  But this might influence performance.

Can you take a look?

[1]:
```
"pool-4-thread-1@7757" prio=5 tid=0x17 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for pool-4-thread-3@7761 to release lock on <0x1fa4> (a java.lang.Object)
	  at com.amazonaws.xray.entities.EntityImpl.getId(EntityImpl.java:233)
	  at com.amazonaws.xray.entities.SubsegmentImpl.getStreamSerializeObjectNode(SubsegmentImpl.java:132)
	  - locked <0x1fc5> (a java.lang.Object)
	  at com.amazonaws.xray.entities.SubsegmentImpl.streamSerialize(SubsegmentImpl.java:143)
	  at com.amazonaws.xray.emitters.UDPEmitter.sendSubsegment(UDPEmitter.java:97)
	  at com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:120)
	  at com.amazonaws.xray.strategy.DefaultStreamingStrategy.streamSome(DefaultStreamingStrategy.java:87)
	  at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:593)
	  at com.amazonaws.xray.interceptors.TracingInterceptor.afterExecution(TracingInterceptor.java:288)
	  at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$afterExecution$11(ExecutionInterceptorChain.java:192)
```

[2]:
```
"pool-4-thread-3@7761" prio=5 tid=0x19 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks pool-4-thread-1@7757
	 blocks pool-4-thread-2@7758
	 blocks pool-4-thread-4@7762
	 blocks pool-4-thread-5@7763
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:917)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1240)
	  at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:267)
	  at com.amazonaws.xray.entities.EntityImpl.addSubsegment(EntityImpl.java:537)
	  - locked <0x1fa4> (a java.lang.Object)
	  at com.amazonaws.xray.contexts.ThreadLocalSegmentContext.beginSubsegment(ThreadLocalSegmentContext.java:52)
	  at com.amazonaws.xray.AWSXRayRecorder.beginSubsegment(AWSXRayRecorder.java:614)
	  at com.amazonaws.xray.interceptors.TracingInterceptor.beforeExecution(TracingInterceptor.java:225)
	  at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$beforeExecution$1(ExecutionInterceptorChain.java:62)
```

**Comment by willarmiros** [comment]
Hi @steven-aerts,

Thanks for raising this issue, we will investigate and try to reproduce it so we can put out a fix. We'll post any updates here.
