### ISSUE TITLE
No op implementation

### ISSUE THREAD

**Issue by grobmeier** [aws/aws-xray-sdk-java#30]
It would be great to have "no op" implementation for at least the AWSXRayServletFilter. So far it is impossible (or I didn't see how to do it yet) to disable XRay for local development without touching the web.xml or Spring boot filter code. Having an environment flag would be helpful.

**Comment by haotianw465** [comment]
Thank you for your feedback. This no-op mode is in our backlog. In the meantime is having environment variable `AWS_XRAY_CONTEXT_MISSING` set to `LOG_ERROR` an acceptable workaround for your local development? You can see more details here: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-envvars. Please let me know your thoughts.

**Comment by grobmeier** [comment]
Thanks @haotianw465 . Unfortunately, AWS_XRAY_CONTEXT_MISSING does not work in my environment. I set it as environment variable, tried the system property and finally did something like:

```
AWSXRayRecorder recorder = builder.build();
recorder.setContextMissingStrategy(new LogErrorContextMissingStrategy());
```

None of these settings prevented the exception to mess up my log. Is there anything I miss here?

My setup is a typical maven project, I am running the tomcat7 plugin. I tried to configure that as well, like:

```
<configuration>
                    <port>8080</port>
                    <path>/</path>
                    <contextFile>src/main/deploy-resources/META-INF/context.xml</contextFile>
                    <systemProperties>
<com.amazonaws.xray.strategy.contextMissingStrategy>LOG_ERROR</com.amazonaws.xray.strategy.contextMissingStrategy>
                    </systemProperties>
```

Unfortunately to no success. Any pointer would be fantastic.

**Comment by haotianw465** [comment]
Hi, could you provide the stack trace when you set `AWS_XRAY_CONTEXT_MISSING`? This looks like an issue in the SDK that needs to be fixed.

**Comment by grobmeier** [comment]
Of course. Thanks for looking into it.

```
2018-09-21 21:57:41,003 [pool-3-thread-1] ERROR [] RulePoller                     - Encountered error polling GetSamplingRules:
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 127.0.0.1:2000 [/127.0.0.1] failed: Connection refused (Connection refused)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1134) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1080) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.doInvoke(AWSXRayClient.java:1257) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.invoke(AWSXRayClient.java:1226) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.invoke(AWSXRayClient.java:1215) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.executeGetSamplingRules(AWSXRayClient.java:568) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.getSamplingRules(AWSXRayClient.java:539) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.pollRule(RulePoller.java:53) ~[aws-xray-recorder-sdk-core-2.0.1.jar:?]
	at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.lambda$start$0(RulePoller.java:41) ~[aws-xray-recorder-sdk-core-2.0.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:2000 [/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.2.jar:4.5.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.conn.$Proxy63.connect(Unknown Source) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.2.jar:4.5.2]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1256) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072) ~[aws-java-sdk-core-1.11.398.jar:?]
	... 20 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.2.jar:4.5.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.conn.$Proxy63.connect(Unknown Source) ~[?:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.2.jar:4.5.2]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1256) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072) ~[aws-java-sdk-core-1.11.398.jar:?]
	... 20 more
```

**Comment by luluzhao** [comment]
@grobmeier , the reason you were having this error is that SDK cannot fetch sampling information from our backend via daemon. Here I attached the [Source Code](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/sampling/pollers/RulePoller.java#L40). Basically, SDK will catch up the exception when fetching sampling information and then log it. In this case, enabling `ContextMissingStrategy` won't solve this issue. If you want to test your application to see how centralized sampling strategy works, you have to install daemon so that SDK can get proper sampling rules and sampling targets. If your tests don't care about sampling, the log error you attached is "harmless" or you can disable centralized sampling strategy by enabling localized one(see example at this link https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html) We will make sure prioritizing `No Op` feature support in future. Please stay tuned.

**Comment by grobmeier** [comment]
Thanks, understood. Looking forward to noop!

**Comment by GregoryOrciuch** [comment]
NoOP would be appreciated :)

**Comment by alexmnyc** [comment]
This is crazy that adding these dependencies auto starts everything when testing locally. There has to be a way to disable it!

**Comment by srprash** [comment]
Hi everyone who +1 the issue. We understand that the no-op feature is definitely needed for the SDK, and its on our backlog. We'll try to get it prioritized and post an update as soon as possible. Meanwhile please stay tuned.

Thanks.

**Comment by GregoryOrciuch** [comment]
> NoOP would be appreciated :) any news here ?

Oh, it's been more then year now since I posted It. So we resigned from x-ray in our AWS project. Instead we use customized CloudWatch metrics. Which is also having similar issue on spring cloudwatch metric starter, it always wants to connected AWS, so this is not a common thing there is no NoOP there. Cheers

**Comment by gitorres** [comment]
This is a shame of course. Only way I found to disable *something* is to unset AWS_XRAY_DAEMON_ADDRESS and set AWS_XRAY_CONTEXT_MISSING to IGNORE_ERROR.

This is not ideal, since it keeps trying to produce traces.
