### ISSUE TITLE
Deadlock in DefaultStreamingStrategy when ending a subsegment with many threads on the same Segment

### ISSUE THREAD

**Issue by Kurru** [aws/aws-xray-sdk-java#318]
I have some code that generates many subsegments rapidly using multiple threads. I've observed that they can get dead locked on each other due to the EntityImpl.isInProgress lock used in DefaultStreamingStrategy. 

It seems to end a subsegment, the code first takes a lock on the subsegment (`AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:630`) then they attempt to check there are no locks on any other subsegment within the Segment associated with the subsegment (`ThreadLocalSegmentContext.endSubsegment(ThreadLocalSegmentContext.java:86`) and eventually `DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:103)`

If 2 different threads attempt to end a subsegment at the same time (for the same segment) AND the segment is large enough to trigger segment streaming, then both threads will lock. In practice, if there are multiple threads working, they will all eventually want to end their segments and thus all outstanding threads interacting with this Segment will also lock waiting for the deadlock to clear.

Thread grpc-default-executor-0
```
"grpc-default-executor-0" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on java.lang.Object@264dd439 owned by "grpc-default-executor-3" Id=74
	at app//com.amazonaws.xray.entities.EntityImpl.isInProgress(EntityImpl.java:483)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:103)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:96)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:96)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:96)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.streamSome(DefaultStreamingStrategy.java:86)
	at app//com.amazonaws.xray.contexts.ThreadLocalSegmentContext.endSubsegment(ThreadLocalSegmentContext.java:86)
	at app//com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:630)
	at app//com.amazonaws.xray.entities.SubsegmentImpl.close(SubsegmentImpl.java:178)
```

Thread grpc-default-executor-3
```
grpc-default-executor-3" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on java.lang.Object@77b7386b owned by "grpc-default-executor-0" Id=43
	at app//com.amazonaws.xray.entities.EntityImpl.isInProgress(EntityImpl.java:483)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:103)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:96)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:96)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.stream(DefaultStreamingStrategy.java:96)
	at app//com.amazonaws.xray.strategy.DefaultStreamingStrategy.streamSome(DefaultStreamingStrategy.java:86)
	at app//com.amazonaws.xray.contexts.ThreadLocalSegmentContext.endSubsegment(ThreadLocalSegmentContext.java:86)
	at app//com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:630)
	at app//com.amazonaws.xray.entities.SubsegmentImpl.close(SubsegmentImpl.java:178)
```

**Comment by Kurru** [comment]
My temporary workaround was to disable the streaming completely.

```
AWSXRay.getGlobalRecorder().setStreamingStrategy(new StreamingStrategy() {
      @Override
      public boolean requiresStreaming(Segment segment) {
        return false;
      }

      @Override
      public void streamSome(Entity entity, Emitter emitter) {
        throw new UnsupportedOperationException();
      }
    });
```

**Comment by willarmiros** [comment]
Hi @Kurru,

Thanks for raising this and providing a temporary workaround, we will take a look into it when we are able. Note that this only appears to impact versions of the SDK later than 2.8.0, so you can also downgrade to that earlier version.

**Comment by Kurru** [comment]
Is there any estimation for this? We suspect this was causing problems in our stack (thread locks causing unreliability and OOM due to stuck resources).

**Comment by willarmiros** [comment]
Hi @Kurru thanks for the ping, we cannot provide an exact ETA but will be prioritizing this soon and will update this issue once the fix is out.

**Comment by Kurru** [comment]
This may have been a problem due to using `Subsegment.close` to end a subsegment from a separate thread. I've run a few high concurrency codepaths and they seem to no longer deadlock. 

It seems using `AWSXray.endSubsegment(subsegment)` works correctly with the `DefaultStreamingStrategy` subsegment streamer.

**Comment by jj22ee** [comment]
Hi @Kurru, glad to see that you’ve resolved the issue. Closing the issue as resolved.

For future reference, the AWSXray.endSubsegment(subsegment) method should be used when ending custom custom subsegments in asynchronous methods or other threads. The subsegment.close() method was not designed for external use.
