### ISSUE TITLE
Periodically conection errors on ElasticBeanstalk

### ISSUE THREAD

**Issue by grobmeier** [aws/aws-xray-sdk-java#44]
I receive segments in my dashboard, but sometimes I have errors like:

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 127.0.0.1:2000 [/127.0.0.1] failed: Connection refused (Connection refused)
```
Sometimes I get things like this:
```
2018-12-05 17:20:17,963 [http-nio-8080-exec-9] ERROR [anonymous] LogErrorContextMissingStrategy - Suppressing AWS X-Ray context missing exception (SegmentNotFoundException): Failed to begin subsegment named 'XXXX': segment cannot be found.
```

which is very annoying. The daemon itself appears to be running fine, but sometimes it looks like connectivity is not really good.

**Comment by awssandra** [comment]
Hi grobmeier,

Can you tell me a bit about your setup? Are you running this locally, or a part of a production stack? What options do you have enabled on the X-Ray SDK? The SDK uses UDP to transmit segment through the Daemon, HTTP requests to the daemon are for fetching rules/targets for centralized sampling support, so I am wondering if there is an issue in that regard.

For issue #2 - the context missing exception means that sometime when handling your request, the X-Ray SDK attempted to add data to the segment in progress, however, for some reason the context was lost. Can you tell me a bit about your web framework and libraries you're using? Are you using a barebones setup or do you have any custom instrumentation?

**Comment by grobmeier** [comment]
I am running the default configuration of ElasticBeanstalk. 
I have looked at the exception a bit further and it seems that it can't poll a sampling rule.

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 127.0.0.1:2000 [/127.0.0.1] failed: Connection refused (Connection refused)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1134) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1080) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515) ~[aws-java-sdk-core-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.doInvoke(AWSXRayClient.java:1257) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.invoke(AWSXRayClient.java:1226) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.invoke(AWSXRayClient.java:1215) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.executeGetSamplingRules(AWSXRayClient.java:568) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.services.xray.AWSXRayClient.getSamplingRules(AWSXRayClient.java:539) ~[aws-java-sdk-xray-1.11.398.jar:?]
	at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.pollRule(RulePoller.java:65) ~[aws-xray-recorder-sdk-core-2.1.0.jar:?]
	at com.amazonaws.xray.strategy.sampling.pollers.RulePoller.lambda$start$0(RulePoller.java:46) ~[aws-xray-recorder-sdk-core-2.1.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
```

I am using the Spring framework and integrated it like:

```
   static {
        AWSXRayRecorderBuilder builder = AWSXRayRecorderBuilder.standard().withPlugin(new EC2Plugin()).withPlugin(new ElasticBeanstalkPlugin());
        AWSXRayRecorder recorder = builder.build();
        recorder.setContextMissingStrategy(new LogErrorContextMissingStrategy());
        AWSXRay.setGlobalRecorder(recorder);
   }
```

However, it seems it is a right problem. I have added "AWSXRayDaemonWriteAccess" to my service role which does have "poll" in it's right. However I am not sure what else it might need so it can get to the rules.

Issue 2 - I think we can kick that for now. It only happened once or twice, so I am ok with that for now.

**Comment by grobmeier** [comment]
Actually this is also probably not like it should be right? I do that from the ElasticBeanstalk EC2 directly:
```

curl -i 127.0.0.1:2000
curl: (7) Failed to connect to 127.0.0.1 port 2000: Connection refused
```

**Comment by haotianw465** [comment]
What is the X-Ray daemon version running on your ElasticBeanstalk EC2? Or providing the ElasticBeanstalk environment platform version also works if you have issue getting the daemon version.

If you have daemon 3.x running you should get something like:

```
curl -I localhost:2000
HTTP/1.1 403 Forbidden
Content-Length: 94
Date: Wed, 05 Dec 2018 20:48:27 GMT
X-Amzn-Requestid: 1d6b4ce6-f8cf-11e8-bc19-c9b1b5ac6fb0
Content-Type: text/plain; charset=utf-8
```
since the 3.x daemon opens a TCP proxy which signs the request and forward it to X-Ray service.

**Comment by grobmeier** [comment]
I have "Tomcat 8 with Java 8 running on 64bit Amazon Linux/2.7.1" and get:

```
xray --version
AWS X-Ray daemon version: 2.0.0
```

I have cloned the current environment with "Tomcat 8 with Java 8 running on 64bit Amazon Linux/3.0.6" and this is my output:

```
xray --version
AWS X-Ray daemon version: 2.0.0
```

Apparantely I do not have 3.0, even with the latest platform. So I went to both versions and tried to update xray manually, but the result was:

```
yum update xray
Loaded plugins: priorities, update-motd, upgrade-helper
...
No packages marked for update
```

The Maven depedencies I use have the version number 2.1.0. Should I downgrade them?

**Comment by haotianw465** [comment]
You can downgrade the SDK but it has latest bug fixes to this is not recommended. You can check the guidance of using X-Ray sampling rules with 2.x SDK and 3.x daemon here: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-sampling. If you decide to not use service sampling rules you can opt-out by configuring `LocalizedSamplingStrategy` using the code snippet shown in the link for configuring the recorder.

We already forwarded the request to AWS Elastic Beanstalk team so they look into have 3.x daemon install on newer version of platforms. If you decide the service sampling rule feature is useful and want to workaround it you can use ebextensions to install the daemon yourself: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-sampling.

Please feel free to let me know any further help you needed.

**Comment by grobmeier** [comment]
Thanks. I am not installing it again until Beanstalk has the 3.x daemon natively.

**Comment by jaypea** [comment]
@grobmeier i've struggled with this as well until i've upgraded the daemon like this

new file: `.ebextensions/xray-daemon.config`
```
option_settings:
    aws:elasticbeanstalk:xray:
        XRayEnabled: true

commands:
    01-stop-tracing:
        command: yum remove -y xray
        ignoreErrors: true
    02-copy-tracing:
        command: curl https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-3.x.rpm -o /home/ec2-user/xray.rpm
    03-start-tracing:
        command: yum install -y /home/ec2-user/xray.rpm

files:
    "/opt/elasticbeanstalk/tasks/taillogs.d/xray-daemon.conf" :
        mode: "000644"
        owner: root
        group: root
        content: |
            /var/log/xray/xray.log
```

**Comment by grobmeier** [comment]
Hi, is there any information on Beanstalk support for this? I find the lack of information very confusing and workaround in such places seem like dangerous.

**Comment by chrisradek** [comment]
@grobmeier 
According to the Elastic Beanstalk [documentation](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.java), it looks like the latest platform versions now include version 3.0.0 of the X-Ray daemon.

**Comment by grobmeier** [comment]
Oh that's awesome to hear @chrisradek 

Thanks for the information and the link. I actually checked but was not able to find it on my own.

I believe this should resolve this issue, since it was caused to outdated version. I will try it and reopen if this is not the case.
