### ISSUE TITLE
AWSXRayServletFilterTest flaky caused random CI build failures

### ISSUE THREAD

**Issue by haotianw465** [aws/aws-xray-sdk-java#48]
An example failed build: https://travis-ci.org/aws/aws-xray-sdk-java/jobs/457711364

```
[ERROR]   AWSXRayServletFilterTest.testNameOverrideSystemProperty:145 
emitter.sendSegment(<Capturing argument>);
Wanted 1 time:
-> at com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest.testNameOverrideSystemProperty(AWSXRayServletFilterTest.java:145)
But was 707 times. Undesired invocation:
-> at com.amazonaws.xray.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:132)
[INFO] 
[ERROR] Tests run: 144, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by haotianw465** [comment]
Another occurrence https://travis-ci.org/aws/aws-xray-sdk-java/jobs/498309753

```
[INFO] Running com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest
Feb 25, 2019 6:34:06 PM com.amazonaws.xray.strategy.FixedSegmentNamingStrategy <init>
INFO: Environment variable AWS_XRAY_TRACING_NAME or system property com.amazonaws.xray.strategy.tracingName set. Overriding FixedSegmentNamingStrategy constructor argument. Segments generated with this strategy will be named: pass.
Feb 25, 2019 6:34:06 PM com.amazonaws.xray.strategy.FixedSegmentNamingStrategy <init>
INFO: Environment variable AWS_XRAY_TRACING_NAME or system property com.amazonaws.xray.strategy.tracingName set. Overriding FixedSegmentNamingStrategy constructor argument. Segments generated with this strategy will be named: pass.
Feb 25, 2019 6:34:06 PM com.amazonaws.xray.strategy.FixedSegmentNamingStrategy <init>
INFO: Environment variable AWS_XRAY_TRACING_NAME or system property com.amazonaws.xray.strategy.tracingName set. Overriding FixedSegmentNamingStrategy constructor argument. Segments generated with this strategy will be named: pass.
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.341 s <<< FAILURE! - in com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest
[ERROR] testAsyncServletRequestWithCompletedAsync(com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest)  Time elapsed: 0.161 s  <<< FAILURE!
org.mockito.exceptions.verification.TooManyActualInvocations: 
emitter.sendSegment(<any>);
Wanted 1 time:
-> at com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest.testAsyncServletRequestWithCompletedAsync(AWSXRayServletFilterTest.java:91)
But was 714 times. Undesired invocation:
-> at com.amazonaws.xray.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:132)
	at com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest.testAsyncServletRequestWithCompletedAsync(AWSXRayServletFilterTest.java:91)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   AWSXRayServletFilterTest.testAsyncServletRequestWithCompletedAsync:91 
emitter.sendSegment(<any>);
Wanted 1 time:
-> at com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest.testAsyncServletRequestWithCompletedAsync(AWSXRayServletFilterTest.java:91)
But was 714 times. Undesired invocation:
-> at com.amazonaws.xray.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:132)
[INFO] 
[ERROR] Tests run: 153, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by chanchiem** [comment]
Another occurrence: https://travis-ci.org/aws/aws-xray-sdk-java/jobs/561114676

```
[INFO] Running com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest
Jul 19, 2019 5:11:56 PM com.amazonaws.xray.strategy.FixedSegmentNamingStrategy <init>
INFO: Environment variable AWS_XRAY_TRACING_NAME or system property com.amazonaws.xray.strategy.tracingName set. Overriding FixedSegmentNamingStrategy constructor argument. Segments generated with this strategy will be named: pass.
Jul 19, 2019 5:11:56 PM com.amazonaws.xray.strategy.FixedSegmentNamingStrategy <init>
INFO: Environment variable AWS_XRAY_TRACING_NAME or system property com.amazonaws.xray.strategy.tracingName set. Overriding FixedSegmentNamingStrategy constructor argument. Segments generated with this strategy will be named: pass.
Jul 19, 2019 5:11:56 PM com.amazonaws.xray.strategy.FixedSegmentNamingStrategy <init>
INFO: Environment variable AWS_XRAY_TRACING_NAME or system property com.amazonaws.xray.strategy.tracingName set. Overriding FixedSegmentNamingStrategy constructor argument. Segments generated with this strategy will be named: pass.
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.724 s <<< FAILURE! - in com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest
[ERROR] testAsyncServletRequestWithCompletedAsync(com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest)  Time elapsed: 0.51 s  <<< FAILURE!
org.mockito.exceptions.verification.TooManyActualInvocations: 
emitter.sendSegment(<any>);
Wanted 1 time:
-> at com.amazonaws.xray.javax.servlet.AWSXRayServletFilterTest.testAsyncServletRequestWithCompletedAsync(AWSXRayServletFilterTest.java:91)
But was 869 times:
-> at com.amazonaws.xray.AWSXRayRecorder.sendSegment(AWSXRayRecorder.java:132)
...
[INFO] 
[ERROR] Tests run: 154, Failures: 1, Errors: 0, Skipped: 0
```
